version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: restore-db
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=store
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U appuser -d store']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
